### ISSUE TITLE
Generic webhook as notification?

### ISSUE THREAD

**Issue by lukasmrtvy** [rycus86/release-watcher#1]
Is possible to implement generic webhook as notification?

**Comment by rycus86** [comment]
Yeah, that sounds like a good idea, and it shouldn't be too hard - but it's not implemented just yet.
Any suggestions on what the payload should look like for generic webhooks?

**Comment by lukasmrtvy** [comment]
Oh, I dont know. I did not even try Your software yet :)

Maybe something like:
```
curl $URL -d '{"Title","New release","Type":"Github","Url","https://github.com/rycus86/release-watcher/","Version","1.0.0"}'
or
curl $URL -d '{"Title","New release","Type":"Dockerhub","Url","https://hub.docker.com/_/nginx","Version","1.14"}'
```

BTW: Is possible to track Tags, Commits in Github mode?

**Comment by rycus86** [comment]
It's tags/releases only at the moment, running a check every now and then (every 4 hours by default), so the granularity is not great for tracking commits.

**Comment by rycus86** [comment]
As discussed above, this is not supported for now.
