### ISSUE TITLE
Helm hub is no longer exists

### ISSUE THREAD

**Issue by lexfrei** [rycus86/release-watcher#11]
Moved to https://artifacthub.io/

**Comment by rycus86** [comment]
Thanks for the update!
Any chance you could capture this in a PR? 🙂

**Comment by lexfrei** [comment]
I'll check it on weekend. Just after Telegram support :)

**Comment by fstarkenberg** [comment]
It would be awesome if support for any Helm registry could be added.

All Helm registries have an index.yaml file in its root that lists charts and versions.
Here are some popular examples:
* Rancher: https://releases.rancher.com/server-charts/latest/index.yaml
* Gitlab: https://charts.gitlab.io/index.yaml
* ingress-nginx: https://kubernetes.github.io/ingress-nginx/index.yaml
* Jetstack: https://charts.jetstack.io/index.yaml

So the idea would be to get the index each CHECK_INTERVAL, check the name (e.g. `name: rancher`) and then `version: 1.2.3`.

Let me know if this belongs in a separate issue or is out of scope 🙂

**Comment by rycus86** [comment]
Happy to review a PR for this idea! :)

**Comment by lexfrei** [comment]
I did a small research on a new artifacthub.io API and it's not working as expected. I got this task on my todo-list but in very low priority.

**Comment by Jonher937** [comment]
Now that the support for checking Helm packages from Artifact Hub has been added this issue can be closed.

---

> It would be awesome if support for any Helm registry could be added.
> 
> All Helm registries have an index.yaml file in its root that lists charts and versions.
> Here are some popular examples:
> 
> * Rancher: https://releases.rancher.com/server-charts/latest/index.yaml
> * Gitlab: https://charts.gitlab.io/index.yaml
> * ingress-nginx: https://kubernetes.github.io/ingress-nginx/index.yaml
> * Jetstack: https://charts.jetstack.io/index.yaml
> 
> So the idea would be to get the index each CHECK_INTERVAL, check the name (e.g. `name: rancher`) and then `version: 1.2.3`.
> 
> Let me know if this belongs in a separate issue or is out of scope

If there is still a need for the above, I guess it belongs in a new issue
