### ISSUE TITLE
Docker hub image updates notifications

### ISSUE THREAD

**Issue by ChrisB85** [rycus86/release-watcher#3]
Is there a way to get notifications about image updates of the same tag? For example: I would like to recieve notifications about updates of image with "latest" tag. Is it possible?

**Comment by rycus86** [comment]
It's not supported at the moment, but technically it could be possible.
It could get messy when you're image points to a manifest that points to multiple images, like https://hub.docker.com/v2/repositories/rycus86/autobump/tags/latest

If this was added as a feature, how would you want to configure it?

**Comment by rycus86** [comment]
Closing this for now, feel free to reopen it if you have more input to this issue. Thanks!

**Comment by ChrisB85** [comment]
Sorry for inactivity. Diun uses nice way to configure notifications for single tags of docker images https://github.com/crazy-max/diun/blob/master/doc/configuration.md

**Comment by rycus86** [comment]
No worries! So the multiple tag watching is supported here too, but not tracking the SHA changes of the same tag, e.g. `latest`.
My problem with it is that not all tags just point to a single image, some will be a multi-arch manifest, having an image for each architecture it supports (`amd64`, `arm`, etc)
Would you want a webhook on any change, or all changes, or only for some architecture?

Still doable, just trying to work out needs so the configuration can be just complex enough, and not more complex than it needs to be. :)
